// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google()
        maven { url 'https://maven.aliyun.com/repository/public/' }  // 阿里云 Maven 镜像
        mavenCentral()
        jcenter()  // 可选，部分依赖可能需要
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
    }
}

