pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}
// AGP 7+不需要再在build.gradle中设置allprojects
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "FlexMusicPlayer"
include ':app'
include ':feature_player'
include ':feature_transcode'
include ':feature_search'
include ':feature_download'
include ':core_domain'
include ':core_data'
include ':core_network'
include ':core_database'
