apply plugin: 'com.android.library'

android {
    namespace 'com.example.feature_player'
    compileSdk 34

    defaultConfig {
        minSdk 21

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
        externalNativeBuild {
            cmake {
                cppFlags '-std=c++17'
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    externalNativeBuild {
        cmake {
            path file('../native/CMakeLists.txt')
            version '3.22.1'
        }
    }
    sourceSets {
        main {
            jniLibs.srcDirs = [
                    '../native/third_party/ffmpeg/libs',
                    '../native/third_party/flac/libs',
                    '../native/third_party/oggvorbis/libs',
                    '../native/third_party/mp3lame/libs'
            ]
        }
    }
}

dependencies {

    implementation libs.appcompat
    implementation libs.material
    implementation project(":core_domain")
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}
